// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type GetAgentsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentsError = GetAgentsErrors[keyof GetAgentsErrors];

export type GetAgentsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type CreateAgentData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type CreateAgentErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors];

export type CreateAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type DeleteAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type GetAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type UpdateAgentData = {
    body?: {
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type UpdateAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors];

export type UpdateAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses];

export type GetAgentToolInvocationPoliciesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}/tool-invocation-policies';
};

export type GetAgentToolInvocationPoliciesErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentToolInvocationPoliciesError = GetAgentToolInvocationPoliciesErrors[keyof GetAgentToolInvocationPoliciesErrors];

export type GetAgentToolInvocationPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetAgentToolInvocationPoliciesResponse = GetAgentToolInvocationPoliciesResponses[keyof GetAgentToolInvocationPoliciesResponses];

export type UnassignToolInvocationPolicyFromAgentData = {
    body?: never;
    path: {
        id: string;
        policyId: string;
    };
    query?: never;
    url: '/api/agents/{id}/tool-invocation-policies/{policyId}';
};

export type UnassignToolInvocationPolicyFromAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UnassignToolInvocationPolicyFromAgentError = UnassignToolInvocationPolicyFromAgentErrors[keyof UnassignToolInvocationPolicyFromAgentErrors];

export type UnassignToolInvocationPolicyFromAgentResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type UnassignToolInvocationPolicyFromAgentResponse = UnassignToolInvocationPolicyFromAgentResponses[keyof UnassignToolInvocationPolicyFromAgentResponses];

export type AssignToolInvocationPolicyToAgentData = {
    body?: never;
    path: {
        id: string;
        policyId: string;
    };
    query?: never;
    url: '/api/agents/{id}/tool-invocation-policies/{policyId}';
};

export type AssignToolInvocationPolicyToAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type AssignToolInvocationPolicyToAgentError = AssignToolInvocationPolicyToAgentErrors[keyof AssignToolInvocationPolicyToAgentErrors];

export type AssignToolInvocationPolicyToAgentResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type AssignToolInvocationPolicyToAgentResponse = AssignToolInvocationPolicyToAgentResponses[keyof AssignToolInvocationPolicyToAgentResponses];

export type GetAgentTrustedDataPoliciesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}/trusted-data-policies';
};

export type GetAgentTrustedDataPoliciesErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentTrustedDataPoliciesError = GetAgentTrustedDataPoliciesErrors[keyof GetAgentTrustedDataPoliciesErrors];

export type GetAgentTrustedDataPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetAgentTrustedDataPoliciesResponse = GetAgentTrustedDataPoliciesResponses[keyof GetAgentTrustedDataPoliciesResponses];

export type UnassignTrustedDataPolicyFromAgentData = {
    body?: never;
    path: {
        id: string;
        policyId: string;
    };
    query?: never;
    url: '/api/agents/{id}/trusted-data-policies/{policyId}';
};

export type UnassignTrustedDataPolicyFromAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UnassignTrustedDataPolicyFromAgentError = UnassignTrustedDataPolicyFromAgentErrors[keyof UnassignTrustedDataPolicyFromAgentErrors];

export type UnassignTrustedDataPolicyFromAgentResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type UnassignTrustedDataPolicyFromAgentResponse = UnassignTrustedDataPolicyFromAgentResponses[keyof UnassignTrustedDataPolicyFromAgentResponses];

export type AssignTrustedDataPolicyToAgentData = {
    body?: never;
    path: {
        id: string;
        policyId: string;
    };
    query?: never;
    url: '/api/agents/{id}/trusted-data-policies/{policyId}';
};

export type AssignTrustedDataPolicyToAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type AssignTrustedDataPolicyToAgentError = AssignTrustedDataPolicyToAgentErrors[keyof AssignTrustedDataPolicyToAgentErrors];

export type AssignTrustedDataPolicyToAgentResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type AssignTrustedDataPolicyToAgentResponse = AssignTrustedDataPolicyToAgentResponses[keyof AssignTrustedDataPolicyToAgentResponses];

export type GetChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type GetChatsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        hashForId: string | null;
        agentId: string;
        createdAt: string;
        updatedAt: string;
        interactions: Array<{
            id: string;
            chatId: string;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
             */
            content: {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'developer';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'system';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'image_url';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                     */
                    image_url: {
                        url: string;
                        detail: 'auto' | 'low' | 'high';
                    };
                } | {
                    type: 'input_audio';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                     */
                    input_audio: {
                        data: string;
                        format: 'wav' | 'mp3';
                    };
                } | {
                    type: 'file';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                     */
                    file: {
                        file_data?: string;
                        file_id?: string;
                        filename?: string;
                    };
                }>;
                role: 'user';
                name?: string;
            } | {
                role: 'assistant';
                audio?: {
                    id: string;
                } | null;
                content?: string | Array<{
                    type: 'text';
                    text: string;
                }> | Array<{
                    type: 'refusal';
                    refusal: string;
                }> | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                name?: string;
                refusal?: string | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            } | {
                role: 'tool';
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                tool_call_id: string;
            } | {
                role: 'function';
                content: string | null;
                name: string;
            };
            tainted: boolean;
            taintReason: string | null;
            createdAt: string;
        }>;
    }>;
};

export type GetChatsResponse = GetChatsResponses[keyof GetChatsResponses];

export type CreateChatData = {
    body: {
        hashForId?: string | null;
        agentId: string;
    };
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type CreateChatResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        hashForId: string | null;
        agentId: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type GetChatData = {
    body?: never;
    path: {
        chatId: string;
    };
    query?: never;
    url: '/api/chats/{chatId}';
};

export type GetChatErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        hashForId: string | null;
        agentId: string;
        createdAt: string;
        updatedAt: string;
        interactions: Array<{
            id: string;
            chatId: string;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
             */
            content: {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'developer';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'system';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'image_url';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                     */
                    image_url: {
                        url: string;
                        detail: 'auto' | 'low' | 'high';
                    };
                } | {
                    type: 'input_audio';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                     */
                    input_audio: {
                        data: string;
                        format: 'wav' | 'mp3';
                    };
                } | {
                    type: 'file';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                     */
                    file: {
                        file_data?: string;
                        file_id?: string;
                        filename?: string;
                    };
                }>;
                role: 'user';
                name?: string;
            } | {
                role: 'assistant';
                audio?: {
                    id: string;
                } | null;
                content?: string | Array<{
                    type: 'text';
                    text: string;
                }> | Array<{
                    type: 'refusal';
                    refusal: string;
                }> | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                name?: string;
                refusal?: string | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            } | {
                role: 'tool';
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                tool_call_id: string;
            } | {
                role: 'function';
                content: string | null;
                name: string;
            };
            tainted: boolean;
            taintReason: string | null;
            createdAt: string;
        }>;
    };
};

export type GetChatResponse = GetChatResponses[keyof GetChatResponses];

export type DeleteApiProxyOpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/proxy/openai/';
};

export type DeleteApiProxyOpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiProxyOpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/proxy/openai/';
};

export type GetApiProxyOpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadApiProxyOpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/proxy/openai/';
};

export type HeadApiProxyOpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsApiProxyOpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/proxy/openai/';
};

export type OptionsApiProxyOpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchApiProxyOpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/proxy/openai/';
};

export type PatchApiProxyOpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiProxyOpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/proxy/openai/';
};

export type PostApiProxyOpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutApiProxyOpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/proxy/openai/';
};

export type PutApiProxyOpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteApiProxyOpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/proxy/openai/{*}';
};

export type DeleteApiProxyOpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiProxyOpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/proxy/openai/{*}';
};

export type GetApiProxyOpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadApiProxyOpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/proxy/openai/{*}';
};

export type HeadApiProxyOpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsApiProxyOpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/proxy/openai/{*}';
};

export type OptionsApiProxyOpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchApiProxyOpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/proxy/openai/{*}';
};

export type PatchApiProxyOpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiProxyOpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/proxy/openai/{*}';
};

export type PostApiProxyOpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutApiProxyOpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/proxy/openai/{*}';
};

export type PutApiProxyOpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OpenAiChatCompletionsData = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1487
     */
    body: {
        model: string;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
         */
        messages: Array<{
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'developer';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'system';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            } | {
                type: 'image_url';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                 */
                image_url: {
                    url: string;
                    detail: 'auto' | 'low' | 'high';
                };
            } | {
                type: 'input_audio';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                 */
                input_audio: {
                    data: string;
                    format: 'wav' | 'mp3';
                };
            } | {
                type: 'file';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                 */
                file: {
                    file_data?: string;
                    file_id?: string;
                    filename?: string;
                };
            }>;
            role: 'user';
            name?: string;
        } | {
            role: 'assistant';
            audio?: {
                id: string;
            } | null;
            content?: string | Array<{
                type: 'text';
                text: string;
            }> | Array<{
                type: 'refusal';
                refusal: string;
            }> | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
             */
            function_call?: {
                arguments: string;
                name: string;
            } | null;
            name?: string;
            refusal?: string | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
             */
            tool_calls?: Array<{
                id: string;
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                 */
                function: {
                    arguments: string;
                    name: string;
                };
            } | {
                id: string;
                type: 'custom';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                 */
                custom: {
                    input: string;
                    name: string;
                };
            }>;
        } | {
            role: 'tool';
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            tool_call_id: string;
        } | {
            role: 'function';
            content: string | null;
            name: string;
        }>;
        /**
         *
         * A function tool that can be used to generate a response.
         *
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
         *
         */
        tools?: Array<{
            type: 'function';
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
             */
            function: {
                name: string;
                description?: string;
                /**
                 *
                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                 *
                 * The parameters the functions accepts, described as a JSON Schema object. See the
                 * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                 * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                 * documentation about the format.
                 *
                 * Omitting parameters defines a function with an empty parameter list.
                 *
                 */
                parameters?: {
                    [key: string]: unknown;
                };
                strict?: boolean | null;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        }>;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
         */
        tool_choice?: 'none' | 'auto' | 'required' | {
            type: 'allowed_tools';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
             */
            allowed_tools: {
                /**
                 *
                 * Constrains the tools available to the model to a pre-defined set.
                 *
                 * auto allows the model to pick from among the allowed tools and generate a
                 * message.
                 *
                 * required requires the model to call one or more of the allowed tools.
                 *
                 */
                mode: 'auto' | 'required';
                /**
                 * A list of tool definitions that the model should be allowed to call
                 */
                tools: Array<{
                    [key: string]: {
                        type: 'function';
                        /**
                         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                         */
                        function: {
                            name: string;
                            description?: string;
                            /**
                             *
                             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                             *
                             * The parameters the functions accepts, described as a JSON Schema object. See the
                             * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                             * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                             * documentation about the format.
                             *
                             * Omitting parameters defines a function with an empty parameter list.
                             *
                             */
                            parameters?: {
                                [key: string]: unknown;
                            };
                            strict?: boolean | null;
                        };
                    };
                }>;
            };
        } | {
            type: 'function';
            function: {
                name: string;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        };
        temperature?: number | null;
        max_tokens?: number | null;
        stream?: boolean | null;
    };
    headers: {
        /**
         * If specified, interactions will be associated with this chat, otherwise a new chat will be created
         */
        'x-archestra-chat-id'?: string;
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * Bearer token for OpenAI
         */
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/proxy/openai/chat/completions';
};

export type OpenAiChatCompletionsErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type OpenAiChatCompletionsError = OpenAiChatCompletionsErrors[keyof OpenAiChatCompletionsErrors];

export type OpenAiChatCompletionsResponses = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L248
     */
    200: {
        id: string;
        choices: Array<{
            finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
            index: number;
            logprobs: unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
             */
            message: {
                content: string | null;
                refusal: string | null;
                role: 'assistant';
                annotations?: Array<unknown>;
                audio?: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            };
        }>;
        created: number;
        model: string;
        object: 'chat.completion';
        server_tier?: string;
        system_fingerprint?: string;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
         */
        usage?: {
            completion_tokens: number;
            prompt_tokens: number;
            total_tokens: number;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
             */
            completion_tokens_details?: unknown;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
             */
            prompt_tokens_details?: unknown;
        };
    };
};

export type OpenAiChatCompletionsResponse = OpenAiChatCompletionsResponses[keyof OpenAiChatCompletionsResponses];

export type GetToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools';
};

export type GetToolsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolsError = GetToolsErrors[keyof GetToolsErrors];

export type GetToolsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        agentId: string;
        name: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description: string | null;
        allowUsageWhenUntrustedDataIsPresent: boolean;
        dataIsTrustedByDefault: boolean;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetToolsResponse = GetToolsResponses[keyof GetToolsResponses];

export type UpdateToolData = {
    body?: {
        id?: string;
        agentId?: string;
        name?: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description?: string | null;
        allowUsageWhenUntrustedDataIsPresent?: boolean;
        dataIsTrustedByDefault?: boolean;
        createdAt?: unknown;
        updatedAt?: unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tools/{id}';
};

export type UpdateToolErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateToolError = UpdateToolErrors[keyof UpdateToolErrors];

export type UpdateToolResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        name: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description: string | null;
        allowUsageWhenUntrustedDataIsPresent: boolean;
        dataIsTrustedByDefault: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateToolResponse = UpdateToolResponses[keyof UpdateToolResponses];

export type GetOperatorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/operators';
};

export type GetOperatorsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        value: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        label: string;
    }>;
};

export type GetOperatorsResponse = GetOperatorsResponses[keyof GetOperatorsResponses];

export type GetToolInvocationPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/tool-invocation';
};

export type GetToolInvocationPoliciesErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolInvocationPoliciesError = GetToolInvocationPoliciesErrors[keyof GetToolInvocationPoliciesErrors];

export type GetToolInvocationPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetToolInvocationPoliciesResponse = GetToolInvocationPoliciesResponses[keyof GetToolInvocationPoliciesResponses];

export type CreateToolInvocationPolicyData = {
    body: {
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/tool-invocation';
};

export type CreateToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateToolInvocationPolicyError = CreateToolInvocationPolicyErrors[keyof CreateToolInvocationPolicyErrors];

export type CreateToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateToolInvocationPolicyResponse = CreateToolInvocationPolicyResponses[keyof CreateToolInvocationPolicyResponses];

export type DeleteToolInvocationPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type DeleteToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteToolInvocationPolicyError = DeleteToolInvocationPolicyErrors[keyof DeleteToolInvocationPolicyErrors];

export type DeleteToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteToolInvocationPolicyResponse = DeleteToolInvocationPolicyResponses[keyof DeleteToolInvocationPolicyResponses];

export type GetToolInvocationPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type GetToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolInvocationPolicyError = GetToolInvocationPolicyErrors[keyof GetToolInvocationPolicyErrors];

export type GetToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetToolInvocationPolicyResponse = GetToolInvocationPolicyResponses[keyof GetToolInvocationPolicyResponses];

export type UpdateToolInvocationPolicyData = {
    body?: {
        toolId?: string;
        argumentName?: string;
        operator?: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value?: string;
        action?: 'allow_when_context_is_untrusted' | 'block_always';
        reason?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type UpdateToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateToolInvocationPolicyError = UpdateToolInvocationPolicyErrors[keyof UpdateToolInvocationPolicyErrors];

export type UpdateToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateToolInvocationPolicyResponse = UpdateToolInvocationPolicyResponses[keyof UpdateToolInvocationPolicyResponses];

export type GetTrustedDataPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/trusted-data-policies';
};

export type GetTrustedDataPoliciesErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetTrustedDataPoliciesError = GetTrustedDataPoliciesErrors[keyof GetTrustedDataPoliciesErrors];

export type GetTrustedDataPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetTrustedDataPoliciesResponse = GetTrustedDataPoliciesResponses[keyof GetTrustedDataPoliciesResponses];

export type CreateTrustedDataPolicyData = {
    body: {
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
    };
    path?: never;
    query?: never;
    url: '/api/trusted-data-policies';
};

export type CreateTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateTrustedDataPolicyError = CreateTrustedDataPolicyErrors[keyof CreateTrustedDataPolicyErrors];

export type CreateTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateTrustedDataPolicyResponse = CreateTrustedDataPolicyResponses[keyof CreateTrustedDataPolicyResponses];

export type DeleteTrustedDataPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type DeleteTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteTrustedDataPolicyError = DeleteTrustedDataPolicyErrors[keyof DeleteTrustedDataPolicyErrors];

export type DeleteTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTrustedDataPolicyResponse = DeleteTrustedDataPolicyResponses[keyof DeleteTrustedDataPolicyResponses];

export type GetTrustedDataPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type GetTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetTrustedDataPolicyError = GetTrustedDataPolicyErrors[keyof GetTrustedDataPolicyErrors];

export type GetTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetTrustedDataPolicyResponse = GetTrustedDataPolicyResponses[keyof GetTrustedDataPolicyResponses];

export type UpdateTrustedDataPolicyData = {
    body?: {
        toolId?: string;
        description?: string;
        attributePath?: string;
        operator?: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type UpdateTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateTrustedDataPolicyError = UpdateTrustedDataPolicyErrors[keyof UpdateTrustedDataPolicyErrors];

export type UpdateTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateTrustedDataPolicyResponse = UpdateTrustedDataPolicyResponses[keyof UpdateTrustedDataPolicyResponses];
